poems = [
  {
    id: 0,
    text: "Madáretető",
    body: [
      "Cinkék, cinegék, feketerigók,",
      "megosztom veletek e fél cipót,",
      "megosztom az én olyan-amilyen",
      "énekem-szerzett kenyerem.",
      " ",
      "Csettegess, rigóm, járd a kerteket,",
      "jöjjetek, csókák, varjak, verebek:",
      "vendégül látok minden itt maradt,",
      "velünk telelő madarat.",
      " ",
      "Terítve már patyolat abroszom,",
      "kenyeremet elétek morzsolom.",
      "Nem várok érte, nem kell félnetek,",
      "ordas télben ujjongó éneket.",
      " ",
      "Ha majd tavasz lesz, és én hallgatok,",
      "akkor zendüljön a ti hangotok,",
      "hírrel hirdetve, hogy az emberek",
      "télen se voltak embertelenek. "
    ]
  },
  {
    id: 1,
    text: "Kánikula",
    body: [
      "Kutyameleg, kánikula,",
      "nyelvét kiveti a kutya,",
      "budákol, a tűző, heves",
      "nap elől árnyékot keres.",
      "",
      "De alighogy hűvösre lel",
      "s leheverne, költözni kell:",
      "falja az árnyékot a nap,",
      "s az ebbe is beleharap.",
      "",
      "Pillognak a récék, libák,",
      "nem csinálnak most galibát;",
      "kiapadt a kicsi patak,",
      "mint a cérna, kettészakadt.",
      "",
      "Itt-ott ha még van is, ami",
      "víznek mondható valami,",
      "odamennek a bivalyok,",
      "s kimártják a kis patakot.",
      "",
      "Egyedül egy árva csacsi",
      "hangját lehet csak hallani,",
      "megereszt egy bátor iá-t,",
      "esőért az égre kiált. "
    ]
  },
  {
    id: 2,
    text: "Pacsirta",
    body: [
      "Pacsirta zeng a magasban, gyűrűzik",
      "hangjától a levegő; lüktető",
      "köröcskék pengetik a nap",
      "feszes sugarait.",
      "",
      "Zeng, zeng a pacsirta, óceánra",
      "menekült kis kalózadó,",
      "s azt sugározza egyre,",
      "fáradhatatlanul,",
      "hogy milyen rettenetes éjszakánként",
      "egy magányosan didergő kökénybokor",
      "alján virrasztani. "
    ]
  },
  {
    id: 3,
    text: "Elnémult a kis patak",
    body: [
      "Elnémult a kis patak,",
      "elakadt a hangja,",
      "jég födte be s a jeget",
      "öles hó takarja.",
      "",
      "Azt se tudnád, hol lehet,",
      "merre volt a medre,",
      "partja közét a nagy hó",
      "színültig befedte.",
      "",
      "De a füzek, az öreg",
      "girbe-gurba strázsák,",
      "az elnémult patakot",
      "télen is vigyázzák.",
      "",
      "Ösvény is fut rajta friss,",
      "naponta-vert ösvény,",
      "hogyha volna korcsolyám,",
      "magam is felkötném.",
      "",
      "Beállnék a gyermekek",
      "vidám seregébe,",
      "s tavaszt-hozó verseket",
      "karcolnék a jégre."
    ]
  },
  {
    id: 4,
    text: "Kakukk",
    body: [
      "Nem szeretem a kakukkmadarat,",
      "mert folyton-folyvást egyet hajtogat:",
      "kakukk, kakukk, kakukk.",
      "",
      "Mintha az erdő egyesegyedül",
      "az övé volna, szégyentelenül",
      "fújja a magáét: kakukk, kakukk.",
      "",
      "Túlkiabál minden más madarat,",
      "csak harsogja a nyári ég alatt:",
      "kakukk, kakukk, kakukk.",
      "",
      "Ő mondja meg, hogy meddig élhetek,",
      "kisajátít idegen fészkeket,",
      "abba tojik a szemtelen kakukk.",
      "",
      "Hallgat az erdő, bölcsen bólogat:",
      "szeretni kell mindenegy madarat,",
      "akkor is, ha kakukk.   ",
      "",
      "Hatalmas az ég, végtelen a nyár,",
      "s ideje a kakukknak is lejár,",
      "elnémul, bereked.",
      "",
      "És újra hallod majd a cinegék,",
      "pintyek, rigók kedves kis énekét",
      "s a locska verebet. "
    ]
  },
  {
    id: 5,
    text: "Erdőn jártam",
    body: [
      "Erdőn jártam,",
      "málnát szedtem,",
      "amit szedtem,",
      "mind megettem,",
      "üres a kaska,",
      "mit csináljak,",
      "mit mondjak anyámnak,",
      "ha megkérdi,",
      "hol a málna,",
      "miért üres",
      "a kosárka?",
      "Azt mondjam-e,",
      "jött egy medve,",
      "amit szedtem,",
      "mind megette?",
      "Dehogy mondom,",
      "megijedne.",
      "Jujj! "
    ]
  },
  {
    id: 6,
    text: "Elment Péter",
    body: [
      "Elment Péter tököt venni, ",
      "elfelejtett pénzzel menni. ",
      "Hogy a sült tök? Ennyi s ennyi. ",
      "De nem volt mit elővenni. ",
      " ",
      "Elmaradt a sülttök-vétel,",
      "étlen maradt szegény Péter.'"
    ]
  },
  {
    id: 7,
    text: "Valaki jár a fák hegyén",
    body: [
    "valaki jár a fák hegyén",
      "ki gyújtja s oltja csillagod",
      "csak az nem fél kit a remény",
      "már végképp magára hagyott",
      "",
      "én félek még reménykedem",
      "ez a megtartó irgalom",
      "a gondviselő félelem",
      "kísért eddigi utamon",
      "",
      "valaki jár a fák hegyén",
      "vajon amikor zuhanok",
      "meggyújt-e akkor még az én",
      "tüzemnél egy új csillagot",
      "",
      "vagy engem is egyetlenegy",
      "sötétlő maggá összenyom",
      "s nem villantja föl lelkemet",
      "egy megszülető csillagon",
      "",
      "valaki jár a fák hegyén",
      "mondják úr minden porszemen",
      "mondják hogy maga a remény",
      "mondják maga a félelem",
  ]
  }
];

export default poems;
